import numpy as np

# quick method to convert first letter of string to lowercase (eg. for concatenating labels)
def lc(s): return s[:1].lower() + s[1:]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Ensembles etc

cmip5_13 = ["ACCESS1-3_r1i1p1", "BCC-CSM1-1_r1i1p1", "CCSM4_r1i1p1", "CESM1-BGC_r1i1p1", "CMCC-CM_r1i1p1", "CNRM-CM5_r1i1p1", "CanESM2_r1i1p1", "EC-EARTH_r1i1p1", "GFDL-ESM2G_r1i1p1", "HadGEM2-ES_r1i1p1", "IPSL-CM5A-MR_r1i1p1", "MPI-ESM-MR_r1i1p1", "MRI-CGCM3_r1i1p1"]

cmip5_ec = ["CNRM-CM5_r1i1p1", "EC-EARTH_r12i1p1", "EC-EARTH_r1i1p1", "EC-EARTH_r3i1p1", "HadGEM2-ES_r1i1p1", "IPSL-CM5A-MR_r1i1p1", "MPI-ESM-LR_r1i1p1", "MPI-ESM-LR_r2i1p1", "MPI-ESM-LR_r3i1p1", "NorESM1-M_r1i1p1"]

periods = ['19801201-20101130', '19891201-20191130', '19991201-20291130', '20091201-20391130', '20191201-20491130', '20291201-20591130', '20391201-20691130', '20491201-20791130']

sea = { "DJF" : "winter", "JJA" : "summer", "MAM" : "spring", "SON" : "autumn"}

gcm_full_names = {"CNRM-CM5_r1i1p1" : "CNRM-CERFACS-CNRM-CM5_r1i1p1",
                  "EC-EARTH_r12i1p1" : "ICHEC-EC-EARTH_r12i1p1", 
                  "EC-EARTH_r1i1p1" : "ICHEC-EC-EARTH_r1i1p1", 
                  "EC-EARTH_r3i1p1" : "ICHEC-EC-EARTH_r3i1p1",
                  "ERAINT_r1i1p1" : "ECMWF-ERAINT_r1i1p1",
                  "HadGEM2-ES_r1i1p1" : "MOHC-HadGEM2-ES_r1i1p1", 
                  "IPSL-CM5A-MR_r1i1p1" : "IPSL-IPSL-CM5A-MR_r1i1p1", 
                  "MPI-ESM-LR_r1i1p1" : "MPI-M-MPI-ESM-LR_r1i1p1", 
                  "MPI-ESM-LR_r2i1p1" : "MPI-M-MPI-ESM-LR_r2i1p1",
                  "MPI-ESM-LR_r3i1p1" : "MPI-M-MPI-ESM-LR_r3i1p1",
                  "NorESM1-M_r1i1p1" : "NCC-NorESM1-M_r1i1p1"}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ecs = {"CNRM-CM5" : 3.28, "EC-EARTH" : 3.3, "IPSL-CM5A-MR" : 4.11, "MPI-ESM-LR" : 3.66, "NorESM1-M" : 2.87, "HadGEM2-ES" : 4.6,
       "ACCESS1-3" : np.nan, "bcc-csm1-1" : 2.9, "CanESM2" : 3.7, "CCSM4" : 2.9, "CESM1-BGC" : np.nan, "CMCC-CM" : np.nan, "GFDL-ESM2G" : 2.34, "MPI-ESM-MR" : 3.51, "MRI-CGCM3" : 2.61}
tcr = {"CNRM-CM5" : 1.97, "EC-EARTH" : 2.0, "IPSL-CM5A-MR" : 1.98, "MPI-ESM-LR" : 2.03, "NorESM1-M" : 1.39, "HadGEM2-ES" : 2.43,
       "ACCESS1-3" : np.nan, "bcc-csm1-1" : 1.76, "CanESM2" : 2.30, "CCSM4" : np.nan, "CESM1-BGC" : 1.71, "CMCC-CM" : 1.98, "GFDL-ESM2G" : 1.21, "MPI-ESM-MR" : 2.03, "MRI-CGCM3" : 1.52}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# build dictionary of 30-year time slices based on warming levels

def warming_slices(lvl = None):
    
    wl_df = pd.read_csv("/data/met/processing/20_warming-levels/warming-levels.csv", index_col = 0)
    ws = {"wl"+str(dw) : {run : str(int(wl)-16)+"1201-"+str(int(wl)+14)+"1130" for run, wl in zip(wl_df.index.values.tolist(), wl_df["wl"+str(dw)].values.tolist()) if not np.isnan(wl)} for dw in [1.5, 2, 3, 4]}
    
    if lvl in [1.5, 2, 3, 4]:
        return ws["wl"+str(lvl)]
    else:
        return ws
    

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Controlled vocabulary for variables (loosely based on https://github.com/ukcp-data/UKCP18_CVs/blob/master/UKCP18_CVs/UKCP18_variable.json)

vcmaps = {"pr" : "RdBu", 
          "pr_r" : "RdBu_r",
          "temp" : "RdBu_r", 
          "temp_r" : "RdBu",
          "wind" : "PuOr",
          "wind_r" : "PuOr_r",
          "agri" : "PRGn", 
          "agri_r" : "PRGn_r",
          "other" : "PuOr"}

var_cv = {"cdd": { "plot_label": "Cooling degree-days", 
                   "label_units": "", 
                   "units": "1",
                   "cmap" : vcmaps["temp"]
                 },
          "clt": { "description": "Total cloud", 
                   "label_units": "%", 
                   "long_name": "Cloud area fraction",
                   "plot_label": "Total cloud (%)", 
                   "standard_name": "cloud_area_fraction", 
                   "units": "%",
                   "cmap" : "PuOr" ,
                  "cell_methods": "time: mean",
                 },
          "csdi": { "description": "Number of cold spell days",
                      "label_units": "",
                      "level": "1.5m",
                      "long_name": "Number of cold spell days",
                      "plot_label": "Number of cold spell days",
                      "units": "day",
                      "cmap" : vcmaps["temp_r"]
                    },
          "drizzleprop": { "plot_label": "Percentage of rain falling on low-intensity days", 
                    "label_units": "%", "units": "%",
                   "cmap" : vcmaps["pr"]
                 },
          "dsmax": { "plot_label": "Maximum length of dry spell (days)", 
                    "label_units": "", "units": "1",
                   "cmap" : vcmaps["pr_r"]
                 },
          "dsmed": { "plot_label": "Median length of dry spell (days)", 
                     "label_units": "", "units": "1",
                   "cmap" : vcmaps["pr_r"]
                 },
          "dtr": { "plot_label": "Diurnal temperature range tasmax - tasmin (°C)", 
                    "label_units": "°C", "units": "degC",
                   "cmap" : "PuOr_r"
                 },
          "fwd": { "description": "Percentage of wet days", 
                   "label_units": "%", 
                   "long_name": "Percentage of wet days",
                   "plot_label": "Percentage of wet days", 
                   "standard_name": "wet_day_fraction", 
                   "units": "%",
                   "cmap" : vcmaps["pr"]
                 },
          "gdd": { "plot_label": "Growing degree-days", 
                    "label_units": "", "units": "1",
                   "cmap" : vcmaps["agri"]
                 },
          "gsl": { "plot_label": "Growing season length (days)", 
                    "label_units": "", "units": "1",
                   "cmap" : vcmaps["agri"]
                 },
          "hdd": { "plot_label": "Heating degree-days", 
                    "label_units": "", "units": "1",
                   "cmap" : vcmaps["temp_r"]
                 },
          "hurs": { "description": "Relative humidity",
                    "label_units": "%",
                    "level": "1.5m",
                    "long_name": "Relative humidity", 
                    "plot_label": "Relative humidity at 1.5m (%)", 
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "cell_methods": "time:mean",
                    "notes": ["Post-process from instantaneous temp and spec humidity", "Use WPS for LS1-3"],
                    "cmap" : "PuOr_r" 
                  },
          "huss": { "description": "Specific humidity", 
                    "label_units": "1", "level": "1.5m",
                    "long_name": "Specific humidity",
                    "plot_label": "Specific humidity at 1.5m",
                    "standard_name": "specific_humidity",
                    "units": "1",
                    "cmap" : "PuOr_r",
                   "cell_methods": "time: mean",
                  },
          "hwdi": { "description": "Number of heatwave days",
                      "label_units": "",
                      "level": "1.5m",
                      "long_name": "Number of heatwave days",
                      "plot_label": "Number of heatwave days",
                      "units": "day",
                      "cmap" : vcmaps["temp"]
                    },
          "jetlat": { "description": "Jet stream latitude", 
                      "label_units": "degrees latitude",
                      "long_name": "Latitude of eddy-driven jet",
                      "plot_label": "Jet stream latitude (degrees latitude)",
                      "time_averaging": ["5-day rolling average"],
                      "units": "degrees"
                    },
          "jetstr": { "description": "Jet stream strength",
                      "label_units": "m s-1",
                      "long_name": "Strength of eddy-driven jet",
                      "plot_label": "Jet stream strength (m s-1)",
                      "time_averaging": ["5-day rolling average"],
                      "units": "m s-1"
                    },
          "maxsfcWindmax": { "description": "Maximum sustained wind speed",
                       "label_units": "m s-1",
                       "level": "10m",
                       "long_name": "Maximum sustained wind speed at 10m",
                       "plot_label": "Maximum sustained wind speed at 10m (m s-1)",
                       "standard_name": "??",
                       "units": "m s-1",
                       "cmap" : vcmaps["wind"]
                     },
          "maxsfcWindmaxloc": {"plot_label": "Location parameter for GEV fitted to\nmaximum daily wind speed (m/s)",
                      "standard_name": "location_parameter",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : vcmaps["wind"]
                    },
          "maxsfcWindmaxscale": {"plot_label": "Scale parameter for GEV fitted to\nmaximum  daily wind speed (m/s)",
                      "standard_name": "scale_parameter",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : "viridis" 
                    },
          "maxsfcWindmaxshape": {"plot_label": "Shape parameter for GEV fitted to\nmaximum daily wind speed (m/s)",
                      "standard_name": "shape_parameter",
                      "label_units": "", "units": "1",
                      "cmap" : "viridis" 
                    },
          "maxsfcWindmaxrl20": {"plot_label": "20-year return level for GEV fitted to\nmaximum daily wind speed (m/s)",
                      "standard_name": "rl20",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : vcmaps["wind"]
                    },
          "maxsfcWindmaxrl50": {"plot_label": "50-year return level for GEV fitted to\nmaximum daily wind speed (m/s)",
                      "standard_name": "rl50",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : vcmaps["wind"]
                    },
          "maxsfcWindmaxrp20": {"plot_label": "Return period for current\n1-in-20-year maximum daily wind speed",
                      "standard_name": "rp20",
                      "label_units": "", "units": "1",
                      "cmap" : vcmaps["wind_r"]
                    },
          "maxsfcWindmaxrp50": {"plot_label": "50-year return period for current\n1-in-50-year maximum daily wind speed",
                      "standard_name": "rp50",
                      "label_units": "", "units": "1",
                      "cmap" : vcmaps["wind_r"]
                    },
          "maxwsgsmax": { "description": "Maximum gust speed",
                       "label_units": "m s-1",
                       "level": "10m",
                       "long_name": "Maximum gust speed at 10m",
                       "plot_label": "Maximum gust speed at 10m (m s-1)",
                       "standard_name": "??",
                       "units": "m s-1",
                       "cmap" : vcmaps["wind"]
                     },
          "maxwsgsmaxloc": {"plot_label": "Location parameter for GEV fitted to\nmaximum daily gust speed (m/s)",
                      "standard_name": "location_parameter",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : vcmaps["wind"]
                    },
          "maxwsgsmaxscale": {"plot_label": "Scale parameter for GEV fitted to\nmaximum  daily gust speed (m/s)",
                      "standard_name": "scale_parameter",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : "viridis" 
                    },
          "maxwsgsmaxshape": {"plot_label": "Shape parameter for GEV fitted to\nmaximum daily gust speed (m/s)",
                      "standard_name": "shape_parameter",
                      "label_units": "", "units": "1",
                      "cmap" : "viridis" 
                    },
          "maxwsgsmaxrl20": {"plot_label": "20-year return level for GEV fitted to\nmaximum daily gust speed (m/s)",
                      "standard_name": "rl20",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : vcmaps["wind"]
                    },
          "maxwsgsmaxrl50": {"plot_label": "50-year return level for GEV fitted to\nmaximum daily gust speed (m/s)",
                      "standard_name": "rl50",
                      "label_units": "m s-1", "units": "m s-1",
                      "cmap" : vcmaps["wind"]
                    },
          "maxwsgsmaxrp20": {"plot_label": "Return period for current\n1-in-20-year maximum daily gust speed",
                      "standard_name": "rp20",
                      "label_units": "", "units": "1",
                      "cmap" : vcmaps["wind_r"]
                    },
          "maxwsgsmaxrp50": {"plot_label": "50-year return period for current\n1-in-50-year maximum daily gust speed",
                      "standard_name": "rp50",
                      "label_units": "", "units": "1",
                      "cmap" : vcmaps["wind_r"]
                    },
          "maxtmax":{ "description": "Maximum air temperature on the hottest day",
                     "label_units": "°C",
                     "level": "1.5m",
                     "long_name": "Maximum air temperature on the hottest day",
                     "plot_label": "Maximum air temperature on the hottest day at 1.5m (°C)",
                     "standard_name": "air temperature",
                     "units": "degC",
                     "cmap" : vcmaps["temp"]
                    },
          "mintmin":{"description": "Minimum air temperature on the coldest day",
                     "label_units": "°C",
                     "level": "1.5m",
                     "long_name": "Minimum air temperature on the coldest day",
                     "plot_label": "Minimum air temperature on the coldest day at 1.5m (°C)",
                     "standard_name": "air temperature",
                     "units": "degC",
                     "cmap" : vcmaps["temp"]
                    },
          "mrso" : { "plot_label": "Mean soil moisture at a depth of up to 1m",
                    "label_units": "kg m-2", "units" : "kg m-2",
                     "cmap" : "RdBu"},
          "naodjf": { "description": "Average DJF pressure gradient between Gibraltar and Iceland",
                      "label_units": "hPa",
                      "long_name": "Winter atlantic pressure gradient",
                      "plot_label": "Average DJF pressure gradient between Gibraltar and Iceland (hPa)",
                      "units": "hPa" 
                    },
          "ncalm": { "description": "Number of calm days (< 2m/s)",
                     "label_units": "1",
                     "long_name": "Number of calm days",
                     "plot_label": "Number of calm days",
                     "units": "1",
                     "cmap": vcmaps["wind_r"]
                    },
          "ndhi": { "description": "Number of dangerously warm days (hi > 32°C)",
                     "label_units": "1",
                     "long_name": "Number of dangerously warm days (hi > 32°C)",
                     "plot_label": "Number of dangerously warm days (hi > 32°C)",
                     "units": "1",
                     "cmap": vcmaps["temp"]
                    },
          "nwindy": { "description": "Number of windy days (> 10.8m/s)",
                     "label_units": "1",
                     "long_name": "Number of windy days",
                     "plot_label": "Number of windy days",
                     "units": "1",
                     "cmap": vcmaps["wind"]
                    },
          "pdd": {"plot_label": "Percentage of dry days followed by another dry day",
                  "label_units": "%", "units": "%",
                  "cmap" : vcmaps["pr_r"]
                 },
          "pww": {"plot_label": "Percentage of wet days followed by another wet day",
                  "label_units": "%", "units": "%",
                  "cmap" : vcmaps["pr"]
                 },
          "pet": { "description": "Potential evapotranspiration (mm)",
                  "label_units": "mm",
                  "long_name": "Potential evapotranspiration (mm)",
                  "plot_label": "Accumulated PET (mm)",
                  "units": "mm",
                  "cmap" : vcmaps["temp"]
                 },
          "pr": { "description": "Precipitation rate",
                  "label_units": "mm/day",
                  "long_name": "Precipitation rate",
                  "notes": ["Precip mass flux (kg/m²/s, STASH 05216) is numerically equivalent to precip volume flux (mm³/mm²/s = mm/s), assuming constant water density of 1000 kg/m³.",
                            "Use WPS for LS1-3"],
                  "plot_label": "Precipitation rate (mm/day)",
                  "standard_name": "lwe_precipitation_rate",
                  "units": "mm/day",
                  "cmap" : vcmaps["pr"],
                  "cell_methods": "time: mean",
                },
          "prc": { "description": "Convective precipitation rate",
                   "label_units": "mm/day",
                   "long_name": "Convective precipitation rate",
                   "plot_label": "Convective precipitation rate (mm/day)",
                   "units": "mm/day",
                   "cmap" : vcmaps["pr"]
                 },
          "prf": { "description": "Non-convective precipitation rate",
                   "label_units": "mm/day",
                   "long_name": "Non-convective precipitation rate",
                   "plot_label": "Non-convective precipitation rate (mm/day)",
                   "units": "mm/day",
                   "cmap" : vcmaps["pr"]
                 },
          "prcprop": { "description": "Percentage of rainfall due to convection",
                       "label_units": "%",
                       "long_name": "Percentage of rainfall due to convection",
                       "plot_label": "Percentage of rainfall due to convection",
                       "units": "%",
                       "cmap" : vcmaps["pr"]
                 },
          "prcptot": { "description": "Accumulated precipitation",
                       "label_units": "mm",
                       "long_name": "Accumulated precipitation",
                       "plot_label": "Accumulated precipitation (mm)",
                       "units": "mm",
                       "cmap" : vcmaps["pr"]
                 },
          "pr1day": { "description": "1-day total precipitation",
                      "label_units": "mm",
                      "long_name": "Precipitation",
                      "plot_label": "1-day total precipitation (mm)",
                      "standard_name": "precipitation_amount",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "pr5day": { "description": "5-day total precipitation",
                      "label_units": "mm",
                      "long_name": "Precipitation",
                      "plot_label": "5-day total precipitation (mm)",
                      "standard_name": "precipitation_amount",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "prsn": { "description": "Snowfall flux at surface",
                  "label_units": "mm/day",
                  "long_name": "Snowfall flux",
                  "plot_label": "Snowfall flux at surface (mm/day)",
                  "standard_name": "snowfall_flux",
                  "units": "mm/day",
                  "cmap" : vcmaps["pr"],
                   "cell_methods": "time: mean",
                },
          "psl": { "description": "Sea level pressure",
                 "label_units": "hPa",
                 "long_name": "Pressure at mean sea level", 
                 "plot_label": "Sea level pressure (hPa)",
                 "standard_name": "air_pressure_at_sea_level",
                 "units": "hPa",
                 "cmap" : "PuOr_r",
                  "cell_methods": "time: mean",
               },
          "r95": { "description": "95th percentile of daily precipitation rate",
                       "label_units": "mm",
                       "long_name": "95th percentile of daily precipitation rate",
                       "plot_label": "95th percentile of daily precipitation (mm/day)",
                       "units": "mm/day",
                       "cmap" : vcmaps["pr"]
                     },
          "r99": { "description": "99th percentile of daily precipitation rate",
                       "label_units": "mm",
                       "long_name": "99th percentile of daily precipitation rate",
                       "plot_label": "99th percentile of daily precipitation (mm/day)",
                       "units": "mm/day",
                       "cmap" : vcmaps["pr"]
                     },
          "r95ptot": { "description": "Percentage of precipitation falling on days exceeding 95th percentile",
                       "label_units": "%",
                       "long_name": "Percentage of precipitation falling on days exceeding 95th percentile",
                       "plot_label": "Percentage of precipitation (%)",
                       "units": "%",
                       "cmap" : vcmaps["pr"]
                     },
          "r99ptot": { "description": "Percentage of precipitation falling on days exceeding 99th percentile",
                       "label_units": "%",
                       "long_name": "Percentage of precipitation falling on days exceeding 99th percentile",
                       "plot_label": "Percentage of precipitation (%)",
                       "units": "%",
                       "cmap" : vcmaps["pr"]
                     },
          "rls": { "description": "Net surface long wave flux",
                   "label_units": "W m-2",
                   "long_name": "Net surface long wave flux",
                   "plot_label": "Net surface long wave flux (W m-2)",
                   "standard_name": "surface_net_downward_longwave_flux",
                   "units": "W m-2",
                   "cmap" : "PuOr_r",
                  "cell_methods": "time: mean",
                 },
          "rsds": { "description": "Total downward shortwave flux",
                    "label_units": "W m-2",
                    "long_name": "Downward surface shortwave flux",
                    "plot_label": "Total downward shortwave flux (W m-2)",
                    "standard_name": "surface_downwelling_shortwave_flux_in_air",
                    "units": "W m-2",
                    "cmap" : "PuOr_r" 
                  },
          "rss": { "description": "Net surface short wave flux",
                   "label_units": "W m-2",
                   "long_name": "Net surface short wave flux",
                   "plot_label": "Net surface short wave flux (W m-2)",
                   "standard_name": "surface_net_downward_shortwave_flux",
                   "units": "W m-2",
                   "cmap" : "PuOr_r",
                  "cell_methods": "time: mean",
                 },
          "rx1day": { "description": "Maximum 1-day precipitation",
                      "label_units": "mm",
                      "long_name": "Maximum 1-day precipitation",
                      "plot_label": "Maximum 1-day precipitation (mm)",
                      "standard_name": "precipitation_amount",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx1dayloc": { "description": "Location parameter for GEV fitted to maximum 1-day precipitation",
                      "label_units": "mm",
                      "long_name": "Location parameter for GEV fitted to maximum 1-day precipitation",
                      "plot_label": "Location parameter for GEV fitted to\nmaximum 1-day precipitation (mm)",
                      "standard_name": "location_parameter",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx1dayscale": { "description": "Scale parameter for GEV fitted to maximum 1-day precipitation",
                      "label_units": "mm",
                      "long_name": "Scale parameter for GEV fitted to maximum 1-day precipitation",
                      "plot_label": "Scale parameter for GEV fitted to\nmaximum 1-day precipitation (mm)",
                      "standard_name": "scale_parameter",
                      "units": "mm",
                      "cmap" : "PuOr_r" 
                    },
          "rx1dayshape": { "description": "Shape parameter for GEV fitted to maximum 1-day precipitation",
                      "label_units": "1",
                      "long_name": "Shape parameter for GEV fitted to maximum 1-day precipitation",
                      "plot_label": "Shape parameter for GEV fitted to\nmaximum 1-day precipitation",
                      "standard_name": "shape_parameter",
                      "units": "1",
                      "cmap" : "PuOr_r" 
                    },
          "rx1dayrl20": { "description": "20-year return level for GEV fitted to maximum 1-day precipitation",
                      "label_units": "mm",
                      "long_name": "20-year return level for GEV fitted to maximum 1-day precipitation",
                      "plot_label": "20-year return level for GEV fitted to\nmaximum 1-day precipitation (mm)",
                      "standard_name": "rl20",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx1dayrl50": { "description": "50-year return level for GEV fitted to maximum 1-day precipitation",
                      "label_units": "mm",
                      "long_name": "50-year return level for GEV fitted to maximum 1-day precipitation",
                      "plot_label": "50-year return level for GEV fitted to\nmaximum 1-day precipitation (mm)",
                      "standard_name": "rl50",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx1dayrp20": { "description": "Return period for current 1-in-20-year maximum 1-day precipitation",
                      "label_units": "1",
                      "long_name": "Return period for current 1-in-20-year maximum 1-day precipitation",
                      "plot_label": "Return period for current\n1-in-20-year maximum 1-day precipitation",
                      "standard_name": "rp20",
                      "units": "1",
                      "cmap" : vcmaps["pr_r"]
                    },
          "rx1dayrp50": { "description": "50-year return period for current 1-in-50-year maximum 1-day precipitation",
                      "label_units": "1",
                      "long_name": "50-year return period for current 1-in-50-year maximum 1-day precipitation",
                      "plot_label": "50-year return period for current\n1-in-50-year maximum 1-day precipitation",
                      "standard_name": "rp50",
                      "units": "1",
                      "cmap" : vcmaps["pr_r"]
                    },
          "rx5day": { "description": "Maximum 5-day precipitation",
                      "label_units": "mm",
                      "long_name": "Maximum 5-day precipitation",
                      "plot_label": "Maximum 5-day precipitation (mm)",
                      "standard_name": "precipitation_amount",
                      "units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx5dayloc": { "plot_label": "Location parameter for GEV fitted to\nmaximum 5-day precipitation (mm)",
                      "standard_name": "location_parameter",
                      "label_units": "mm","units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx5dayscale": { "plot_label": "Scale parameter for GEV fitted to\nmaximum 5-day precipitation (mm)",
                      "standard_name": "scale_parameter",
                      "label_units": "mm","units": "mm",
                      "cmap" : "PuOr_r" 
                    },
          "rx5dayshape": { "plot_label": "Shape parameter for GEV fitted to\nmaximum 5-day precipitation",
                      "standard_name": "shape_parameter",
                      "label_units": "", "units": "1",
                      "cmap" : "PuOr_r" 
                    },
          "rx5dayrl20": { "plot_label": "20-year return level for GEV fitted to\nmaximum 5-day precipitation (mm)",
                      "standard_name": "rl20",
                      "label_units": "mm","units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx5dayrl50": { "plot_label": "50-year return level for GEV fitted to\nmaximum 5-day precipitation (mm)",
                      "standard_name": "rl50",
                      "label_units": "mm","units": "mm",
                      "cmap" : vcmaps["pr"]
                    },
          "rx5dayrp20": { "plot_label": "Return period for current\n1-in-20-year maximum 5-day precipitation",
                      "standard_name": "rp20",
                      "label_units": "", "units": "1",
                      "cmap" : vcmaps["pr_r"]
                    },
          "rx5dayrp50": { "plot_label": "50-year return period for current\n1-in-50-year maximum 5-day precipitation",
                      "standard_name": "rp50",
                      "label_units": "", "units": "1",
                      "cmap" : vcmaps["pr_r"]
                    },
          "sdii": { "description": "Standardised daily intensity index",
                    "label_units" : "mm/day",
                    "long_name" : "Standardised daily intensity index",
                    "plot_label" : "Wet-day precipitation rate (mm/day)",
                    "standard_name" : "sdii",
                    "units": "mm/day",
                    "cmap" : vcmaps["pr"]
                  },
          "sfcWind": { "description": "Wind speed",
                       "label_units": "m s-1",
                       "level": "10m",
                       "long_name": "Wind speed at 10m",
                       "notes": ["Look also at post-processing this from daily mean U and V, as output from model may be inconsistent"],
                       "plot_label": "Wind speed at 10m (m s-1)",
                       "standard_name": "wind_speed",
                       "units": "m s-1",
                       "cmap" : vcmaps["wind"],
                      "cell_methods": "time: mean",
                     },
          "sfcWindmax": { "description": "Maximum sustained wind speed",
                       "label_units": "m s-1",
                       "level": "10m",
                       "long_name": "Maximum sustained wind speed at 10m",
                       "plot_label": "Maximum sustained wind speed at 10m (m s-1)",
                       "standard_name": "??",
                       "units": "m s-1",
                       "cmap" : vcmaps["wind"]
                     },
          "snw": { "description": "Amount of snow on the ground",
                   "label_units": "mm",
                   "long_name": "Surface snow amount",
                   "plot_label": "Amount of snow on the ground (mm)",
                   "standard_name": "surface_snow_amount",
                   "units": "mm",
                   "cmap" : vcmaps["pr"],
                  "cell_methods": "time: mean",
                 },
          "spei6": { "description": "6-month standardised precipitation-evapotranspiration index",
                   "label_units": "1",
                   "long_name": "6-month standardised precipitation-evapotranspiration index",
                   "plot_label": "6-month standardised precipitation-evapotranspiration index",
                   "standard_name": "spei6",
                   "units": "1",
                   "cmap" : vcmaps["pr"]
                 },
          "spei6dd": { "description": "Drought duration based on 6-month SPEI",
                   "label_units": "1",
                   "long_name": "SPEI6 drought duration (months)",
                   "plot_label": "$SPI_6$ drought duration",
                   "standard_name": "spei6dd",
                   "units": "months",
                   "cmap" : vcmaps["pr_r"]
                 },
          "spi6": { "description": "6-month standardised precipitation index",
                   "label_units": "1",
                   "long_name": "6-month standardised precipitation index",
                   "plot_label": "6-month standardised precipitation index",
                   "standard_name": "spi6",
                   "units": "1",
                   "cmap" : vcmaps["pr"]
                 },
          "spi6dd": { "description": "Drought duration based on 6-month SPI",
                   "label_units": "1",
                   "long_name": "SPI6 drought duration",
                   "plot_label": "$SPI_6$ drought duration (months)",
                   "standard_name": "spi6dd",
                   "units": "months",
                   "cmap" : vcmaps["pr_r"]
                 },
          "ssi": { "description": "Storm severity index",
                   "label_units": "1",
                   "long_name": "Storm severity index",
                   "plot_label": "Storm severity index",
                   "standard_name": "ssi",
                   "units": "1",
                   "cmap" : vcmaps["wind"]
                 },
          "str": { "plot_label": "Seasonal temperature range tas99 - tas01 (°C)", 
                   "label_units": "°C", "units": "degC",
                   "cmap" : "PuOr_r"
                 },
          "tas": { "description": "Mean air temperature",
                   "label_units": "°C",
                   "level": "1.5m",
                   "long_name": "Mean air temperature",
                   "plot_label": "Mean air temperature at 1.5m (°C)",
                   "standard_name": "air_temperature",
                   "cell_methods": "time: mean",
                   "units": "degC",
                   "cmap" : vcmaps["temp"]
                 },
          "tas01": { "description": "First percentile of mean air temperature",
                   "label_units": "°C",
                   "level": "1.5m",
                   "long_name": "First percentile of mean air temperature",
                   "plot_label": "First percentile of daily mean air temperature at 1.5m (°C)",
                   "standard_name": "air_temperature_q01",
                   "units": "degC",
                   "cmap" : vcmaps["temp"]
                 },
          "tas99": { "description": "99th percentile of mean air temperature",
                   "label_units": "°C",
                   "level": "1.5m",
                   "long_name": "99th percentile of mean air temperature",
                   "plot_label": "99th percentile of daily mean air temperature at 1.5m (°C)",
                   "standard_name": "air_temperature_q99",
                   "units": "degC",
                   "cmap" : vcmaps["temp"]
                 },
          "tasmax": { "description": "Daily maximum air temperature",
                      "label_units": "°C",
                      "level": "1.5m",
                      "long_name": "Maximum air temperature",
                      "plot_label": "Daily maximum air temperature at 1.5m (°C)",
                      "standard_name": "air_temperature",
                      "cell_methods": "time: maximum",
                      "units": "degC",
                      "cmap" : vcmaps["temp"]
                    },
          "tasmin": { "description": "Minimum air temperature",
                      "label_units": "°C",
                      "level": "1.5m",
                      "long_name": "Minimum air temperature",
                      "plot_label": "Daily minimum air temperature at 1.5m (°C)",
                      "standard_name": "air_temperature",
                      "cell_methods": "time: minimum",
                      "units": "degC",
                      "cmap" : vcmaps["temp"]
                    },
          "tmin10p": { "description": "Number of nights below 10th percentile of reference temperatures",
                      "label_units": "",
                      "level": "1.5m",
                      "long_name": "Number of cold nights",
                      "plot_label": "Number of cold nights",
                      "units": "day",
                      "cmap" : vcmaps["temp_r"]
                    },
          "tmax10p": { "description": "Number of days below 10th percentile of reference temperatures",
                      "label_units": "",
                      "level": "1.5m",
                      "long_name": "Number of cold days",
                      "plot_label": "Number of cold days",
                      "units": "day",
                      "cmap" : vcmaps["temp_r"]
                    },
          "tmax90p": { "description": "Number of days above 90th percentile of reference temperatures",
                      "label_units": "",
                      "level": "1.5m",
                      "long_name": "Number of hot days",
                      "plot_label": "Number of hot days",
                      "units": "day",
                      "cmap" : vcmaps["temp"]
                    },
          "tmin90p": { "description": "Number of nights above 90th percentile of reference temperatures",
                      "label_units": "",
                      "level": "1.5m",
                      "long_name": "Number of warm nights",
                      "plot_label": "Number of warm nights",
                      "units": "day",
                      "cmap" : vcmaps["temp"]
                    },
          "tr": { "description": "Number of tropical nights",
                      "label_units": "",
                      "long_name": "Number of tropical nights",
                      "plot_label": "Number of tropical nights",
                      "units": "day",
                      "cmap" : vcmaps["temp"]
                    },
          "uas": { "description": "Eastward wind",
                   "label_units": "m s-1",
                   "level": "10m",
                   "long_name": "Eastward wind component",
                   "plot_label": "Eastward wind at 10m (m s-1)",
                   "standard_name": "eastward_wind",
                   "units": "m s-1",
                   "cmap" : vcmaps["wind"],
                  "cell_methods": "time: mean",
                 },
          "vas": { "description": "Northward wind",
                   "label_units": "m s-1",
                   "level": "10m",
                   "long_name": "Northward wind component",
                   "plot_label": "Northward wind at 10m (m s-1)",
                   "standard_name": "northward_wind",
                   "units": "m s-1",
                   "cmap" : vcmaps["wind"],
                  "cell_methods": "time: mean",
                 },
          "wsgsmax": { "description": "Maximum gust speed",
                       "label_units": "m s-1",
                       "level": "10m",
                       "long_name": "Maximum gust speed at 10m",
                       "plot_label": "Maximum gust speed at 10m (m s-1)",
                       "standard_name": "??",
                       "units": "m s-1",
                       "cmap" : vcmaps["wind"]
                     },
          "wsmax": { "plot_label": "Maximum length of wet spell (days)", 
                   "label_units": "", "units": "1",
                   "cmap" : vcmaps["pr"]
                 },
          "wsmed": { "plot_label": "Median length of wet spell (days)", 
                   "label_units": "", "units": "1",
                   "cmap" : vcmaps["pr"]
                 },
          "wtype30": { "description": "Weather type of 30",
                       "label_units": "1",
                       "long_name": "Weather type of 30",
                       "plot_label": "Weather type of 30",
                       "units": "1"
                     },
          "wtype8": { "description": "Weather type of 8",
                      "label_units": "1",
                      "long_name": "Weather type of 8",
                      "plot_label": "Weather type of 8",
                      "units": "1"
                    }
         }


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Controlled vocabulary for model runs (loosely based on https://github.com/ukcp-data/UKCP18_CVs/blob/master/UKCP18_CVs/UKCP18_ensemble_member.json)
# Version in UKCP18 CV will use {v : re.sub("_", "-", k) for k, v in en_cv.items()}

en_cv = {'bcc-csm1-1_r1i1p1': 16,
         'CCSM4_r1i1p1': 17,
         'CESM1-BGC_r1i1p1': 18,
         'CanESM2_r1i1p1': 19,
         'CMCC-CM_r1i1p1': 20,
         'CNRM-CM5_r1i1p1': 21,
         'EC-EARTH_r1i1p1': 22,
         'ACCESS1-3_r1i1p1': 23,
         'HadGEM2-ES_r1i1p1': 24,
         'IPSL-CM5A-MR_r1i1p1': 25,
         'MPI-ESM-MR_r1i1p1': 26,
         'MRI-CGCM3_r1i1p1': 27,
         'GFDL-ESM2G_r1i1p1': 28,
         'EC-EARTH_r12i1p1': 29,
         'MPI-ESM-LR_r1i1p1': 30,
         'MPI-ESM-LR_r2i1p1': 31,
         'MPI-ESM-LR_r3i1p1': 32,
         'NorESM1-M': 33,
         'CNRM-CM5_r1i1p1_ALADIN63': 100,
         'CNRM-CM5_r1i1p1_CCLM4-8-17': 101,
         'CNRM-CM5_r1i1p1_COSMO-crCLIM-v1-1': 102,
         'CNRM-CM5_r1i1p1_HadREM3-GA7-05': 103,
         'CNRM-CM5_r1i1p1_HIRHAM5': 104,
         'CNRM-CM5_r1i1p1_RACMO22E': 105,
         'CNRM-CM5_r1i1p1_RCA4': 106,
         'CNRM-CM5_r1i1p1_RegCM4-6': 107,
         'CNRM-CM5_r1i1p1_REMO2015': 108,
         'CNRM-CM5_r1i1p1_WRF381P': 109,
         'EC-EARTH_r12i1p1_CCLM4-8-17': 110,
         'EC-EARTH_r12i1p1_COSMO-crCLIM-v1-1': 111,
         'EC-EARTH_r1i1p1_COSMO-crCLIM-v1-1': 112,
         'EC-EARTH_r3i1p1_COSMO-crCLIM-v1-1': 113,
         'EC-EARTH_r12i1p1_HadREM3-GA7-05': 114,
         'EC-EARTH_r12i1p1_HIRHAM5': 115,
         'EC-EARTH_r1i1p1_HIRHAM5': 116,
         'EC-EARTH_r3i1p1_HIRHAM5': 117,
         'EC-EARTH_r12i1p1_RACMO22E': 118,
         'EC-EARTH_r1i1p1_RACMO22E': 119,
         'EC-EARTH_r3i1p1_RACMO22E': 120,
         'EC-EARTH_r12i1p1_RCA4': 121,
         'EC-EARTH_r1i1p1_RCA4': 122,
         'EC-EARTH_r3i1p1_RCA4': 123,
         'EC-EARTH_r12i1p1_REMO2015': 124,
         'EC-EARTH_r12i1p1_RegCM4-6': 125,
         'EC-EARTH_r12i1p1_WRF381P': 126,
         'IPSL-CM5A-MR_r1i1p1_HIRHAM5': 127,
         'IPSL-CM5A-MR_r1i1p1_RACMO22E': 128,
         'IPSL-CM5A-MR_r1i1p1_RCA4': 129,
         'IPSL-CM5A-MR_r1i1p1_REMO2015': 130,
         'IPSL-CM5A-MR_r1i1p1_WRF381P': 131,
         'HadGEM2-ES_r1i1p1_ALADIN63': 132,
         'HadGEM2-ES_r1i1p1_CCLM4-8-17': 133,
         'HadGEM2-ES_r1i1p1_COSMO-crCLIM-v1-1': 134,
         'HadGEM2-ES_r1i1p1_HadREM3-GA7-05': 135,
         'HadGEM2-ES_r1i1p1_HIRHAM5': 136,
         'HadGEM2-ES_r1i1p1_RACMO22E': 137,
         'HadGEM2-ES_r1i1p1_RCA4': 138,
         'HadGEM2-ES_r1i1p1_RegCM4-6': 139,
         'HadGEM2-ES_r1i1p1_REMO2015': 140,
         'HadGEM2-ES_r1i1p1_WRF381P': 141,
         'MPI-ESM-LR_r1i1p1_ALADIN63': 142,
         'MPI-ESM-LR_r1i1p1_CCLM4-8-17': 143,
         'MPI-ESM-LR_r1i1p1_COSMO-crCLIM-v1-1': 144,
         'MPI-ESM-LR_r2i1p1_COSMO-crCLIM-v1-1': 145,
         'MPI-ESM-LR_r3i1p1_COSMO-crCLIM-v1-1': 146,
         'MPI-ESM-LR_r1i1p1_HadREM3-GA7-05': 147,
         'MPI-ESM-LR_r1i1p1_HIRHAM5': 148,
         'MPI-ESM-LR_r1i1p1_RACMO22E': 149,
         'MPI-ESM-LR_r1i1p1_RCA4': 150,
         'MPI-ESM-LR_r2i1p1_RCA4': 151,
         'MPI-ESM-LR_r3i1p1_RCA4': 152,
         'MPI-ESM-LR_r1i1p1_RegCM4-6': 153,
         'MPI-ESM-LR_r3i1p1_REMO2015': 154,
         'MPI-ESM-LR_r1i1p1_WRF381P': 155,
         'NorESM1-M_r1i1p1_ALADIN63': 156,
         'NorESM1-M_r1i1p1_COSMO-crCLIM-v1-1': 157,
         'NorESM1-M_r1i1p1_HadREM3-GA7-05': 158,
         'NorESM1-M_r1i1p1_HIRHAM5': 159,
         'NorESM1-M_r1i1p1_RACMO22E': 160,
         'NorESM1-M_r1i1p1_RCA4': 161,
         'NorESM1-M_r1i1p1_RegCM4-6': 162,
         'NorESM1-M_r1i1p1_REMO2015': 163,
         'NorESM1-M_r1i1p1_WRF381P': 164}

